### ISSUE TITLE
Manifest unknown issue after updating the base images to reference the latest Lagoon images 21.4.0

### ISSUE THREAD

**Issue by pandaskii** [govCMS/govcms8lagoon#224]
`docker pull uselagoon/varnish-drupal:21.4.0`

Error response from daemon: manifest for uselagoon/varnish-drupal:21.4.0 not found: manifest unknown: manifest unknown

And 21.4.0 is not available for uselagoon/varnish-drupal:

https://hub.docker.com/r/uselagoon/varnish-drupal/tags?page=1&ordering=last_updated

**Comment by tobybellwood** [comment]
Ok - will fix up over in github.com/uselagoon/lagoon-images to see why the legacy tag hasn't pushed.

You should probably also pull `uselagoon/varnish-5-drupal:21.4.0` to explicitly get the varnish-5 version going forwards.

**Comment by tobybellwood** [comment]
I've re-added `uselagoon/varnish-drupal:21.4.0` manually and identified the fix.

I would recommend pinning to the correct version of the image (ie `varnish-5-drupal`, or even `varnish-6-drupal` now it is available)

**Comment by pandaskii** [comment]
@tobybellwood I am not sure the varnish-5-drupal and varnish-6-drupal, need more advises from @steveworley

**Comment by tobybellwood** [comment]
varnish-5-drupal and varnish-drupal are identical (same digest), but 6 would require testing
