### ISSUE TITLE
NGINX configuration options interfere with generated thumbnails and image styles for uploaded webp images

### ISSUE THREAD

**Issue by iijiang** [govCMS/govcms8lagoon#397]
We are currently experiencing an issue where the WebP thumbnails do not show up due to an NGINX configuration error.

remove webp from here https://github.com/govCMS/lagoon/blob/3.x-develop/.docker/images/nginx/helpers/203-expires.conf#L2?

related issue: https://www.drupal.org/project/drupal/issues/3120676

**Comment by acbramley** [comment]
With https://www.drupal.org/project/drupal/issues/3406267 now shipping in Drupal 10.3.0 this is really needed. Was scratching my head why a new PaaS site wasn't passing image style requests on to Drupal

**Comment by acbramley** [comment]
Oh this is already fixed. Can we close this issue? https://github.com/govcms/lagoon/commit/9d4de3fcddb04563e7081a1bbc81b7e496527444

**Comment by stooit** [comment]
For sure, thanks for the reminder @acbramley, closing this one
